### ISSUE TITLE
订阅大量channel 的时候 fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by ftao** [leizongmin/huobiapi#2]
应该是访问    Makert.listeners  有并发。 
handleMessageLoop  和  Subscribe  两个方法，可能并发的访问 listeners 

```
fatal error: concurrent map read and map write

goroutine 5 [running]:
runtime.throw(0x12af11d, 0x21)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0xc42005bcf0 sp=0xc42005bcd0 pc=0x102ac41
runtime.mapaccess2_faststr(0x1257cc0, 0xc420092cc0, 0xc4205ddbe0, 0x1b, 0xc4205ddbe0, 0x1b)
	/usr/local/go/src/runtime/hashmap_fast.go:270 +0x461 fp=0xc42005bd60 sp=0xc42005bcf0 pc=0x100c641
github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market.(*Market).handleMessageLoop.func1(0xc420550000, 0xa0, 0x600)
	/Users/someuser/go/src/github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market/market.go:147 +0xa75 fp=0xc42005bf90 sp=0xc42005bd60 pc=0x1217d45
github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market.NewSafeWebSocket.func2(0xc42009a140)
	/Users/someuser/go/src/github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market/ws.go:54 +0x48 fp=0xc42005bfd8 sp=0xc42005bf90 pc=0x12183d8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42005bfe0 sp=0xc42005bfd8 pc=0x1055f31
created by github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market.NewSafeWebSocket
	/Users/someuser/go/src/github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market/ws.go:46 +0x118

goroutine 1 [chan receive]:
github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market.(*Market).Subscribe(0xc4200a61e0, 0xc42055c020, 0x15, 0xc420318020, 0x2, 0xc42055c020)
	/Users/someuser/go/src/github.com/xxx/yyyyy/vendor/github.com/leizongmin/huobiapi/market/market.go:237 +0x28d
main.main()
	/Users/someuser/go/src/github.com/xxx/yyyyy/main.go:74 +0x108

```

**Comment by skanger** [comment]
为什么closed掉了，我最近也碰到了这个问题
